package zoologico.view;

import zoologico.control.GestorZoologico;
import zoologico.model.HistoricoTratamento;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import java.time.format.DateTimeFormatter; // Para formatar LocalDate

public class TelaHistoricoTratamento extends javax.swing.JFrame {

    private GestorZoologico gestor;
    private DefaultTableModel tableModel; // Para facilitar a manipulação da tabela
    private DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");

    public TelaHistoricoTratamento(GestorZoologico gestor) {
        this.gestor = gestor;
        initComponents();
        inicializarTabelaHistorico();
        popularTabelaHistorico();
    }

    private void inicializarTabelaHistorico() {
        // Define as colunas da tabela de histórico
        tableModel = new DefaultTableModel(
            new Object[][]{},
            new String[]{"Animal (ID)", "Animal (Nome)", "Veterinário", "Data Tratamento", "Descrição"}
        ) {
            // Torna as células não editáveis
            boolean[] canEdit = new boolean[]{false, false, false, false, false};
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        };
        jTableHistorico.setModel(tableModel); // Defina o nome da sua JTable de histórico aqui
    }

    private void popularTabelaHistorico() {
        tableModel.setRowCount(0); // Limpa a tabela

        List<HistoricoTratamento> historicos = gestor.listarTodoHistoricoTratamentos();

        if (historicos.isEmpty()) {
            System.out.println("Nenhum histórico de tratamento encontrado.");
        } else {
            for (HistoricoTratamento h : historicos) {
                tableModel.addRow(new Object[]{
                    h.getAnimalTratado().getIdentificacao(),
                    h.getAnimalTratado().getNome(),
                    h.getVeterinarioResponsavel().getNome(),
                    h.getDataTratamento().format(dateFormatter), // Formata a data para exibição
                    h.getDescricaoTratamento()
                });
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableHistorico = new javax.swing.JTable(); // Renomeei para jTableHistorico, ajuste o seu design

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Histórico de Tratamentos");

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Histórico de Tratamentos");

        jTableHistorico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableHistorico);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaHistoricoTratamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaHistoricoTratamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaHistoricoTratamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaHistoricoTratamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // Para testar esta tela separadamente, crie um gestor de teste
                GestorZoologico gestorTeste = new GestorZoologico();
                // Opcional: Adicione um histórico de teste aqui para ver dados na tabela
                // Animal animalTeste = gestorTeste.buscarAnimalPorId(1); // Ou crie um animal novo
                // Veterinario vetTeste = (Veterinario) gestorTeste.buscarFuncionarioPorMatricula(301);
                // if (animalTeste != null && vetTeste != null) {
                //     HistoricoTratamento ht = new HistoricoTratamento(animalTeste, vetTeste, LocalDate.now(), "Remédio para febre");
                //     gestorTeste.adicionarHistoricoTratamento(ht);
                // }
                new TelaHistoricoTratamento(gestorTeste).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableHistorico; // Certifique-se que o nome da sua JTable é este
    // End of variables declaration                   
}